// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this;

  module.exports = {
    SourceBuilder: require("./sourceBuilder"),
    TestBuilder: require("./test/testBuilder"),
    component: function(n) {
      return require("./" + n);
    }
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
