// Generated by CoffeeScript 1.4.0
(function() {
  var Image;

  Image = (function() {

    function Image() {}

    Image.prototype.constuctor = function(w, h) {
      this.src = "";
      return this.complete = true;
    };

    return Image;

  })();

  module.exports.image = Image;

}).call(this);
